name: tf-gcp-easy-wg-quick workflow

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          apt-get update
          apt-get install -y --no-install-recommends shellcheck
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: hashicorp/setup-terraform@v1
      - name: tfvars
        id: tfvars
        run: |
          tee terraform.tfvars << EOF
          project          = "prj"
          credentials_file = "/dev/null"
          EOF
      - name: format
        id: fmt
        run: terraform fmt -check
      - name: init
        id: init
        run: terraform init
      - name: validate
        id: validate
        run: terraform validate -no-color
      - name: shellcheck
        run: shellcheck -s bash instance-startup.bash
