name: tf-gcp-easy-wg-quick workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends shellcheck
      - name: checkout
        uses: actions/checkout@v5
      - name: setup
        uses: hashicorp/setup-terraform@v3
      - name: tfvars
        id: tfvars
        run: |
          tee terraform.tfvars << EOF
          project          = "prj"
          credentials_file = "/dev/null"
          EOF
      - name: format
        id: fmt
        run: terraform fmt -check
      - name: init
        id: init
        run: terraform init
      - name: validate
        id: validate
        run: terraform validate -no-color
      - name: shellcheck
        run: shellcheck -a -C -s bash -S style -o all instance-startup.bash
